#!/bin/sh

PROJECT_NAME=`basename $PWD`
echo "Creating new project named: $PROJECT_NAME"

echo "\nPlease edit dependencies in .project/package.js and .project/bower.js before continuing.\n"


echo "Enter w for web project, n for node project:"

read LINE

echo "Installing npm module fs-extra.."
npm install fs-extra

if [ $LINE = "w" ] 
then 
    echo "Copying www and build directories.."
    cp -r ./.project/server ./.project/build ./.project/www ./
    echo "Copying .gitignore"
    cp ./.project/web/.gitignore ./
    echoe "Copying bower.js and package.js"
    cp ./.project/web/package.js ./
    cp ./.project/bower.js ./
    echo "Inserting project name in appropriate places in bower.js."
    sed -i "s/projectname/$PROJECT_NAME/g" ./bower.js
    echo "Creating bower.json.."
    node bower.js
    echo "Installing bower packages.."
    bower install
    echo "Adding $PROJECT_NAME.org"
    cp ./.project/web/project.org $PROJECT_NAME.org
    echo "Adding bin dir"
    cp -r .project/bin ./
else
    echo "Copying .gitignore"
    cp ./.project/.gitignore ./
    echo "Copying package.js"
    cp ./.project/package.js ./
    echo "Adding $PROJECT_NAME.org"
    cp ./.project/project.org $PROJECT_NAME.org
    rm -rf bin
    echo "Adding bin dir"
    mkdir bin
    cp .project/bin/docs ./bin
fi 

rm  js-project.org

echo "Adding README.md.."
cp ./.project/README.md ./

echo "Inserting project name in appropriate places in package.js and README.md."
sed -i "s/projectname/$PROJECT_NAME/g" ./package.js
sed -i "s/projectname/$PROJECT_NAME/g" ./README.md

echo "Creating package.json.."
node package.js
echo "Installing npm packages.."
npm install

if [ $LINE = "n" ] 
then 
    mkdir src
    echo "//Empty source file" > src/$PROJECT_NAME.js
    bin/docs
fi


echo "Removing .project directory"
rm -rf .project

echo "Removing init file"
# chmod uga-x ./init
rm -f init

echo "Removing git repo and creating new.."
rm -rf .git

git init
git add -A
git commit -m 'first commit'
echo "Remote added for michieljoris git user.."
git remote add origin "git@github.com:Michieljoris/$PROJECT_NAME"

echo "Done."

